# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=250)),
                ('level', models.IntegerField()),
                ('vocabulary', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('german_word', models.CharField(max_length=250)),
                ('translation', models.CharField(max_length=250)),
                ('gender', models.CharField(default='Der', max_length=4)),
            ],
        ),
    ]
